### ISSUE TITLE
Skonic breaks literally everything

### ISSUE THREAD

**Issue by Pryzmm** [NagasonicDev/Skonic#1]
All scripts before downloading Skonic give severe skript console errors, and all functions are stated to already exist in the same file
(i.e. "**A global function named 'LoadGame' already exists in script 'Game.sk'**" when reloading the file named Game.sk)

No incompatibility issues were noted, nor any dependencies for Skonic.

Full Plugin List:
**Skonic - v1.0.4**
FastAsyncWorldEdit - build 625
Multiverse-Core - v2.9
Skript - v2.7,3
SkBee - v3.0.1
SkQuery - v4.1.10
ViaVersion - v4.9.2
VoidGen - v2.2.1

Server Info:
Paper version git-Paper-545 (MC: 1.19.4)

**Comment by NagasonicDev** [comment]
Hi, I am currently aware of a multitude of errors in v4, these errors will be fixed in v5, but it will be a while before that version is released, in the meantime I encourage you to be patient until the next update.
