### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Evanbeer** [NagasonicDev/Skonic#2]
Please consider adding pathfinding options for citizen npc's. That's currently the only reason i'm not using this addon. It seems great and it's the only up to date addon for citizens atm.

**Comment by NagasonicDev** [comment]
Yeah, I can do that, the only pathfinding thing RN is the attack effect.

**Comment by Evanbeer** [comment]
Thanks for the quick support guys!
I decided to just make some pathfinding with skript-reflect which happend to be 1 line with citizens nice and clean API.
Still thanks, and keep up with the good work!

**Comment by NagasonicDev** [comment]
Added in version 1.0.7
